### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by Alan963852741** [chetanborse1999/RL-for-Robotic-Control#2]
Sorry for the simple problem.
I'm not sure how to use this code. I try use "python DDPG" on terminal to run it,but it doesn't work. And it comes to this problem:

Traceback (most recent call last):
  File "DDPG.py", line 7, in <module>
    from arm_env import ArmEnv
  File "/home/mhy/RLforRoboticControl/arm_env.py", line 12, in <module>
    from gazebo_pkg.msg import Angles
ImportError: No module named gazebo_pkg.msg

So, could you tell me how to run it?
Best wishes!

**Comment by chetanborse1999** [comment]
Was the package built successfully on 'catkin_make'?

Also check if the custom msg is there using 'rosmsg list'.

**Comment by Alan963852741** [comment]
@chetanborse1999 Actually, when I built it ,I got these problem.

-- +++ processing catkin package: 'gazebo_pkg'
-- ==> add_subdirectory(gazebo_pkg)
-- Could NOT find package1 (missing: package1_DIR)
-- Could not find the required component 'package1'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "package1" with any
  of the following names:

    package1Config.cmake
    package1-config.cmake

  Add the installation prefix of "package1" to CMAKE_PREFIX_PATH or set
  "package1_DIR" to a directory containing one of the above files.  If
  "package1" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  gazebo_pkg/CMakeLists.txt:10 (find_package)

So, is there some way to solve it?
Thanks.

**Comment by chetanborse1999** [comment]
'package1' was a temporary package I made for debugging, but it was made locally. 

I think it should be ok to remove all instances of it from 'CMakeLists.txt' and 'package.xml'.

**Comment by Alan963852741** [comment]
@chetanborse1999 It still does't work. And new problem comes.

-- +++ processing catkin package: 'gazebo_pkg'
-- ==> add_subdirectory(gazebo_pkg)
-- Could NOT find gazebo (missing: gazebo_DIR)
-- Could not find the required component 'gazebo'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  gazebo_pkg/CMakeLists.txt:10 (find_package)

So, is there some way to solve it?
Thanks.

**Comment by chetanborse1999** [comment]
There must be some problem while installing Gazebo. Are you sure it's correctly installed? Or maybe there is a version issue. I am using Gazebo-7 with Ros Kinetic. It is possible that there are a few deprecated functions in my code.

Also run "roslaunch gazebo_pkg start.launch" first and then run DDPG.py in parallel.
